### ISSUE TITLE
Add support for BBA emulation

### ISSUE THREAD

**Issue by Casuallynoted** [libertyernie/NinCFGEditor#1]
Hello! I'd like to request that support be added for the BBA emulation feature, as right now it is not possible to enable it via this tool.

**Comment by Drodericson** [comment]
I second this, it's driving me nuts! Or at least, how would one do it manually?

**Comment by libertyernie** [comment]
I should be able to make this work - this app is just using an older version of the config (8 instead of 10, I think).

Would it be fine if the app only runs on Windows? I'm thinking it would be a little cleaner (and maybe easier for me to update?) if I could add a C++ layer and just copy some of the Nintendont config handling code into it.

**Comment by Drodericson** [comment]
I doesn't bother me if the program only runs on Windows! You code the app the way you think is best!

**Comment by libertyernie** [comment]
https://github.com/libertyernie/Nicoe/releases

Can you try this out? I think it should be able to edit everything that's in the new nincfg.bin.

**Comment by Drodericson** [comment]
All seems to work well! However, could you please allow it to export xml files when the path is set to "di"? This is the path name to autoboot from the disc drive, and currently it throws an error that wont allow the xml to be exported. The original version still threw the error, but it allowed the xml to still be created regardless. I hope this is still possible!

**Comment by libertyernie** [comment]
https://github.com/libertyernie/Nicoe/releases/tag/v10.2

This should work, I think. (Can't really test the "di" thing since my only Wii with a working disc drive is a Wii U.)

I also updated it so it can read and write the older version 8 config files that my old build uses - the way I went about it might be a little too fancy internally, but I didn't want Nicoe to just update all files to version 10 if someone still needed to use the older builds.

**Comment by Drodericson** [comment]
Tested the disc drive on my Wii, it all works perfectly! Thank you so much!
